dist: xenial
language: python
sudo: false

install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
  - python setup.py check -r
after_success:
  - coveralls --verbose

matrix:
  include:
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.7
      env: TOX_ENV=py37
  allow_failures:
    - python: pypy3.5
      env: TOX_ENV=pypy3
