language: python
sudo: false

install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
  - python setup.py check -r
after_success:
  - coveralls --verbose

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: pypy
      env: TOX_ENV=pypy
  allow_failures:
    - python: pypy3
      env: TOX_ENV=pypy3
