name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: |
            3.9
            3.10
            3.11
            pypy3.9
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install six mock request-mock pytest-cov pytest-randam pytest-remove-stale-bytecode
      - name: Run unittest
        run: pytest -v  --random --cov=src --cov-report=term
      - name: flake8
        run: flake8 src
      - name: pycodestyle
        run: pycodestyle -v --first src
      - name: pydocstyle
        run: pydocstyle -v src
      - name: build docs
        run: sphinx-build -M html docs/source doc/build
